### ISSUE TITLE
How do I use this with the package / workspace root being a subdirectory?

### ISSUE THREAD

**Issue by jplatte** [EmbarkStudios/cargo-deny-action#28]
I have a project where there is no `Cargo.toml` at the repository root (all the Rust stuff is in a subdirectory).

I've tried this:

```yaml
jobs:
  cargo-deny:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: api
    steps:
      - uses: actions/checkout@v2
      - uses: EmbarkStudios/cargo-deny-action@v1
```

but it doesn't work (seems like `defaults.run` doesn't apply to cargo-deny-action).

Is there some way to do this with cargo-deny-action as-is, or would this be a new feature?

**Comment by jplatte** [comment]
Ping @repi

**Comment by repi** [comment]
Don't think we've had that use case or tested that. But cargo-deny itself does support passing in, similar to Cargo, a `--manifest-path` to point to the Cargo.toml to run on, so passing that in to the action likely also works.

https://embarkstudios.github.io/cargo-deny/cli/common.html

**Comment by jplatte** [comment]
Thanks. Works with

```yml
      - uses: EmbarkStudios/cargo-deny-action@v1
        with:
          arguments: --manifest-path=api/Cargo.toml
```
