### ISSUE TITLE
Support Windows

### ISSUE THREAD

**Issue by thedataking** [EmbarkStudios/cargo-deny-action#38]
**Is your feature request related to a problem? Please describe.**
This action appears to be Linux-only for the moment. I discovered this by adding it to a Windows Github Actions workflow. Since `cargo-deny` takes about 10m to compile on Github Actions, it needs manual caching which is complicated by the fact that actions/cache@v2 cannot use files outside of the repository root as cache keys.

**Describe the solution you'd like**
Action is updated to support windows.

**Describe alternatives you've considered**
Installing and caching `cargo-deny` as part of the workflow. This is complicated and less ideal than the proposed solution.

Thanks for writing and maintaining this action in the first place!

**Comment by Jake-Shadle** [comment]
cargo-deny is not compiled as part of the action, merely downloaded, so building the docker image, fetching the crates, and running checks typically takes between 1m-2m and more dependent on the size of the crates being fetched than the action itself.

**Comment by thedataking** [comment]
Hi Jake, just to make sure we're not talking past each other. When I try to use the cargo deny action in a Windows workflow, it fails with an error message saying that the action only supports Linux. I then switch to manually provisioning of `cargo-deny`  (not using your action at all) which requires extensive configuration in the workflow. I'm not sure what you mean by this:

 >  so building the docker image, fetching the crates, and running checks typically takes between 1m-2m and more dependent on the size of the crates being fetched than the action itself.

Did you mean that it shouldn't add more than 1-2m to use cargo-deny manually? In my experience, it adds 9-10m to download and compile on the cloud-hosted GitHub runners.

**Comment by Jake-Shadle** [comment]
So I hope that addresses your concern, but as this is a docker based action we don't have any intention of supporting Windows, so if you still want to run cargo-deny on Windows in github actions, you can do something like this (untested):

```yaml
jobs:
  deny:
    name: cargo-deny
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - shell: bash
        run: |
          set -e
          curl -L https://github.com/EmbarkStudios/cargo-deny/releases/download/0.9.1/cargo-deny-0.9.1-x86_64-pc-windows-msvc.tar.gz | tar xzf -
          echo `pwd` >> $GITHUB_PATH
      - run: cargo-deny --all-features check

```
