### ISSUE TITLE
Cannot check private repositories

### ISSUE THREAD

**Issue by danielhaap83** [EmbarkStudios/cargo-deny-action#53]
**Describe the bug**
When my cargo project has a private git repository defined, cargo deny action will fail. Please add possibility to provide a personal access token for git usage.

**To Reproduce**
1. Create cargo crate which references a private git repository
2. Configure deny as usual (defaults are enough)
3. Run 'cargo deny --log-level warn --all-features check bans licenses sources'
4. Fails with:
```sh
[ERROR] `cargo metadata` exited with an error:     Updating crates.io index
    Updating git repository `[https://github.com/private-repo`](https://github.com/private-repo%60)
error: failed to get `private-repo` as a dependency of package `...`
Caused by:
  failed to load source for dependency `private-repo`
...
```

My action.yaml
```yaml
deny:
    name: Deny
    runs-on: ubuntu-latest
    strategy:
      matrix:
        checks:
          - advisories
          - bans licenses sources
    # Prevent sudden announcement of a new advisory from failing ci:
    continue-on-error: ${{ matrix.checks == 'advisories' }}
    steps:
      # checkout this repository
      - name: Checkout
        uses: actions/checkout@v2
      # checkout my private repository - just to show that it works
      - name: Checkout
        uses: actions/checkout@v2
        with:
          repository: private-repo
          path: tmp
          ref: master
          token: ${{ secrets.USER_PAT }}
      - name: Deny
        uses: EmbarkStudios/cargo-deny-action@v1
        with:
          command: check ${{ matrix.checks }}
```

**Expected behavior**
deny should run and check as "normal" and provide its results. It woks also locally using gits credential-helper=store. Please support option to pass token/credentials to cargo-deny-action.
