### ISSUE TITLE
This action doesn't seem to respect the current working directory.

### ISSUE THREAD

**Issue by ctriley** [EmbarkStudios/cargo-deny-action#68]
**Describe the bug**
In github actions, you can set the default folder from which all actions should be run. 
example:
```yaml
name: CI
on: [push, pull_request]
defaults:
  run:
    working-directory: ./rust-app
jobs:
  cargo-deny:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - uses: EmbarkStudios/cargo-deny-action@v1
```

However, this action does not respect the default folder and instead runs from the root directory of the repo.

here is an example repo / workfow:

https://github.com/ctriley/cargo-deny-example/actions/runs/7349611506/job/20009854868

**Comment by antonengelhardt** [comment]
Same issue [here](https://github.com/antonengelhardt/wasm-extensions/actions/runs/7883647418/job/21510997725#step:7:8)...

**Comment by Jake-Shadle** [comment]
The docs for github actions (somewhat) clearly state that working-directory only applies to `.run` actions, the docker run command is not under control of this action (AFAIK) and you can see `/usr/bin/docker run --name eaa03abb2882f8a99948049e12e8fbacd21fc4_1aecb8 --label eaa03a --workdir /github/workspace` where the working directory for the container is always the repo root. I've added the `manifest-path` key to the arguments if you want to use that, or you can also specify `arguments: --manifest-path <path-to-Cargo.toml>` to select whichever Cargo.toml manifest you want.

**Comment by antonengelhardt** [comment]
@Jake-Shadle Thanks a lot!

```
- name: Cargo Deny
        uses: EmbarkStudios/cargo-deny-action@v1
        with:
          manifest-path: extensions/oidc/Cargo.toml
```

worked for me.

When putting 

```
- name: Cargo Deny
        uses: EmbarkStudios/cargo-deny-action@v1
        with:
           arguments: --manifest-path: extensions/oidc/Cargo.toml
```

it says that i cannot define manifest path multiple times.. Or am i misunderstanding your previous comment?
