### ISSUE TITLE
`unable to check for yanked crates` warnings that only appear in github actions

### ISSUE THREAD

**Issue by eric-seppanen** [EmbarkStudios/cargo-deny-action#97]
**Describe the bug**
When run from github actions, I see dozens of `unable to check for yanked crates` warnings from `cargo-deny-action`. If I run `cargo-deny` locally, I don't see any warnings.

All the warnings take the form:
```plaintext
warning[index-failure]: unable to check for yanked crates
   ┌─ /github/workspace/rust/Cargo.lock:12:1
   │
12 │ anyhow 1.0.79 registry+https://github.com/rust-lang/crates.io-index
   │ ------------------------------------------------------------------- crate whose registry we failed to query
   │
   = unable to locate index entry for crate
   = anyhow v1.0.79
```

**To Reproduce**

I'm not sure if this is sufficient to reproduce, but my github actions config looks like this:
```yaml
jobs:
  cargo-deny:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: cargo deny
      uses: EmbarkStudios/cargo-deny-action@v1
      with:
        rust-version: "1.85.0"
        log-level: warn
        command: check licenses bans advisories
        manifest-path: rust/Cargo.toml
```

**Expected behavior**
I expected the same result in github actions that I see locally.

**Screenshots**
n/a

**Device:**
 - OS: github ubuntu 22 runner
